### ISSUE TITLE
SignTool can't sign the driver

### ISSUE THREAD

**Issue by std66** [protaskin/LowCDC-Win10x64#1]
Hello!

First, I'd like to say thanks for your work, it works fine for me. I've successfully installed the driver while Windows 10 (version 1607 x64, build 14393.187) was started without requiring signature verification. But on the next restart the Windows disabled it because it is not signed. So I installed WDK10 in order to run createcat.bat you provided, but it gives me the output that you can find in the attached file. I ran it with administrator rights from the command prompt. Do you have any ideas to solve this issue?

Thank you in advance,
Tamás

[out.txt](https://github.com/protaskin/LowCDC-Win10x64/files/587467/out.txt)

**Comment by protaskin** [comment]
Hello, Tamás.

<blockquote><p>C:\Program Files (x86)\Windows Kits\10\bin\x64>if 0 EQU 1 (if not exist "C:\Users\Tam s\Desktop\LowCDC-Win10x64\certcopy.cer" (</p></blockquote>

> SignTool Error: A certificate chain processed, but terminated in a root
>         certificate which is not trusted by the trust provider.

I presume that you have ran `createcat.bat` at least twice, and the first one without the administrator privileges. So the script successfully created your certificate, but could not add it to the Trusted Root Certification Authorities. Once the file `certcopy.cer` (a copy of the created certificate) is exist, the script assumes that the certificate has been installed properly.

Run Certificate Manager (win+r, `certmgr.msc`), Action → Find Certificates, type "protaskin" in the "Contains" field, submit the form.

If the certificate is installed you should see something like this:
![Certificate Manager](https://cloud.githubusercontent.com/assets/316705/20282037/0f872b5a-aac4-11e6-82d8-c66de645de07.png)

If not, you can install it manually: run `certcopy.cer`, "Install Certificate...", choose Store Location (i would prefer Local Machine), select Trusted Root Certification Authorities, finish the import. Repeat that procedure for Trusted Publishers.

![Certificate Import Wizard](https://cloud.githubusercontent.com/assets/316705/20282831/7810b896-aac7-11e6-9e44-3b019b49555e.png)

Run `lowcdc.cat`, check the status:

![Security Catalog Properties](https://cloud.githubusercontent.com/assets/316705/20283032/74248c98-aac8-11e6-8840-97eb8d6e7ea0.png)

P. S. Sorry for my English, I'm not good at writing.

**Comment by protaskin** [comment]
Also, I'm not quite sure how you were able to install the driver without the signature on Win10 x64.

Windows just complains that the INF file does not contain signature information, regardless of TESTSIGNING value:
![Without signature](https://cloud.githubusercontent.com/assets/316705/20286004/d7150cee-aad5-11e6-9c1e-3d37a34d67f6.png)

A test-signed driver (TESTSIGNING=OFF):
![Test-signed driver (TESTSIGNING=OFF)](https://cloud.githubusercontent.com/assets/316705/20286069/14754518-aad6-11e6-8c13-47e69620528e.png)

A test-signed driver (TESTSIGNING=ON):
![Test-signed driver (TESTSIGNING=ON)](https://cloud.githubusercontent.com/assets/316705/20286113/495d730e-aad6-11e6-8a81-21f2d3cdaa31.png)

At last we can install the driver!

**Comment by std66** [comment]
Oh, you're right, I ran the createcat.bat script without administrator privileges at my first attempt. As I see you also mentioned it in the Russian readme. Sorry, I should have read it more carefully. I'll try your advices at the weekend. Thank you!

**Comment by protaskin** [comment]
No problem. Will be waiting for your feedback.

**Comment by std66** [comment]
Thank you for the help. It works properly now.

**Comment by protaskin** [comment]
I have added checking for administrative privileges (4ff667e), so the problem will not occur henceforth.

Also, have you used the driver for communication with a real device? Could you make a screenshot?

**Comment by std66** [comment]
Yes, I'm using this driver with an STK500 compatible AVR programmer as a physical device:
https://s17.postimg.org/5ftzrv8xr/stk500_device.png

As you can see, the driver is accepted by Windows:
https://s17.postimg.org/wcdz06rr3/devmgmt.png

And the AVR Studio can use the programmer to read and write program from/to the ATmega8:
https://s17.postimg.org/gcvbgmvpb/avrstudio.png

**Comment by protaskin** [comment]
Thanks! I will add them to the readme's screenshot section someday.
